import type { Household, PriceHint, Recipe } from '@amalthea/assistant-core';

/**
 * Synthetic demo data. The Reyes family is invented, frozen for demo
 * consistency: Dana and Sam, kids Ellis (9, peanut allergy) and June (6),
 * $120 weekly budget, taco night as the anchor. Store names are fictional.
 * Recipes are original expression: titles, ingredient lists, tags, and rough
 * costs only, no instructions. Declared allergens are kept a superset of
 * what the allergen table scans from the ingredients (the seed test enforces
 * it), and the table deliberately over-blocks (coconut milk trips the dairy
 * term 'milk'), which the affected recipes declare rather than fight.
 */
export const HOUSEHOLD_ID = 'reyes-demo';

export const household: Omit<Household, 'id'> = {
  name: 'Reyes family',
  weeklyBudget: 120,
  members: [
    { id: 'm-dana', name: 'Dana', allergens: [] },
    { id: 'm-sam', name: 'Sam', allergens: [] },
    { id: 'm-ellis', name: 'Ellis', age: 9, allergens: ['peanut'] },
    { id: 'm-june', name: 'June', age: 6, allergens: [] },
  ],
};

export interface SeedInventoryItem {
  id: string;
  name: string;
  quantity: number;
  unit: string;
  location: 'fridge' | 'freezer' | 'pantry';
  /** Days before the seed run the item was bought. */
  purchasedDaysAgo: number;
  shelfLifeDays: number;
}

export const inventory: SeedInventoryItem[] = [
  // Fridge
  { id: 'i-milk', name: 'milk', quantity: 6, unit: 'cup', location: 'fridge', purchasedDaysAgo: 4, shelfLifeDays: 10 },
  { id: 'i-eggs', name: 'eggs', quantity: 12, unit: 'count', location: 'fridge', purchasedDaysAgo: 5, shelfLifeDays: 28 },
  { id: 'i-cheddar', name: 'cheddar cheese', quantity: 8, unit: 'oz', location: 'fridge', purchasedDaysAgo: 6, shelfLifeDays: 21 },
  { id: 'i-sour-cream', name: 'sour cream', quantity: 1, unit: 'cup', location: 'fridge', purchasedDaysAgo: 10, shelfLifeDays: 21 },
  { id: 'i-butter', name: 'butter', quantity: 16, unit: 'tbsp', location: 'fridge', purchasedDaysAgo: 20, shelfLifeDays: 60 },
  { id: 'i-carrots', name: 'carrots', quantity: 6, unit: 'count', location: 'fridge', purchasedDaysAgo: 8, shelfLifeDays: 30 },
  { id: 'i-celery', name: 'celery', quantity: 6, unit: 'count', location: 'fridge', purchasedDaysAgo: 8, shelfLifeDays: 21 },
  { id: 'i-bell-peppers', name: 'bell peppers', quantity: 2, unit: 'count', location: 'fridge', purchasedDaysAgo: 6, shelfLifeDays: 12 },
  { id: 'i-lettuce', name: 'shredded lettuce', quantity: 1, unit: 'count', location: 'fridge', purchasedDaysAgo: 3, shelfLifeDays: 10 },
  { id: 'i-tomatoes', name: 'tomatoes', quantity: 3, unit: 'count', location: 'fridge', purchasedDaysAgo: 3, shelfLifeDays: 7 },
  { id: 'i-lemons', name: 'lemon', quantity: 2, unit: 'count', location: 'fridge', purchasedDaysAgo: 12, shelfLifeDays: 30 },
  // Freezer
  { id: 'i-ground-beef', name: 'ground beef', quantity: 2, unit: 'lb', location: 'freezer', purchasedDaysAgo: 12, shelfLifeDays: 120 },
  { id: 'i-chicken-thighs', name: 'chicken thighs', quantity: 2, unit: 'lb', location: 'freezer', purchasedDaysAgo: 12, shelfLifeDays: 120 },
  { id: 'i-frozen-peas', name: 'frozen peas', quantity: 2, unit: 'cup', location: 'freezer', purchasedDaysAgo: 30, shelfLifeDays: 240 },
  { id: 'i-frozen-corn', name: 'frozen corn', quantity: 2, unit: 'cup', location: 'freezer', purchasedDaysAgo: 30, shelfLifeDays: 240 },
  { id: 'i-salmon', name: 'salmon', quantity: 1, unit: 'lb', location: 'freezer', purchasedDaysAgo: 18, shelfLifeDays: 90 },
  // Pantry
  { id: 'i-rice', name: 'rice', quantity: 4, unit: 'cup', location: 'pantry', purchasedDaysAgo: 40, shelfLifeDays: 365 },
  { id: 'i-spaghetti', name: 'spaghetti', quantity: 1, unit: 'lb', location: 'pantry', purchasedDaysAgo: 25, shelfLifeDays: 365 },
  { id: 'i-pasta', name: 'pasta', quantity: 1, unit: 'lb', location: 'pantry', purchasedDaysAgo: 25, shelfLifeDays: 365 },
  { id: 'i-black-beans', name: 'black beans', quantity: 2, unit: 'can', location: 'pantry', purchasedDaysAgo: 35, shelfLifeDays: 540 },
  { id: 'i-kidney-beans', name: 'kidney beans', quantity: 1, unit: 'can', location: 'pantry', purchasedDaysAgo: 35, shelfLifeDays: 540 },
  { id: 'i-crushed-tomatoes', name: 'crushed tomatoes', quantity: 56, unit: 'oz', location: 'pantry', purchasedDaysAgo: 35, shelfLifeDays: 540 },
  { id: 'i-chicken-broth', name: 'chicken broth', quantity: 8, unit: 'cup', location: 'pantry', purchasedDaysAgo: 30, shelfLifeDays: 365 },
  { id: 'i-veg-broth', name: 'vegetable broth', quantity: 4, unit: 'cup', location: 'pantry', purchasedDaysAgo: 30, shelfLifeDays: 365 },
  { id: 'i-onions', name: 'onion', quantity: 4, unit: 'count', location: 'pantry', purchasedDaysAgo: 10, shelfLifeDays: 30 },
  { id: 'i-garlic', name: 'garlic', quantity: 12, unit: 'clove', location: 'pantry', purchasedDaysAgo: 15, shelfLifeDays: 60 },
  { id: 'i-potatoes', name: 'potatoes', quantity: 3, unit: 'lb', location: 'pantry', purchasedDaysAgo: 9, shelfLifeDays: 30 },
  { id: 'i-olive-oil', name: 'olive oil', quantity: 32, unit: 'tbsp', location: 'pantry', purchasedDaysAgo: 60, shelfLifeDays: 365 },
  { id: 'i-tortillas', name: 'flour tortillas', quantity: 8, unit: 'count', location: 'pantry', purchasedDaysAgo: 5, shelfLifeDays: 14 },
  { id: 'i-soy-sauce', name: 'soy sauce', quantity: 8, unit: 'tbsp', location: 'pantry', purchasedDaysAgo: 90, shelfLifeDays: 365 },
];

function r(recipe: Recipe): Recipe {
  return recipe;
}

export const recipes: Recipe[] = [
  r({
    id: 'r-taco-night',
    title: 'Family Taco Night',
    ingredients: [
      { name: 'ground beef', quantity: 1.5, unit: 'lb' },
      { name: 'flour tortillas', quantity: 8, unit: 'count' },
      { name: 'cheddar cheese', quantity: 8, unit: 'oz' },
      { name: 'shredded lettuce', quantity: 1, unit: 'count' },
      { name: 'tomatoes', quantity: 2, unit: 'count' },
      { name: 'sour cream', quantity: 0.5, unit: 'cup' },
    ],
    allergens: ['gluten', 'dairy'],
    tags: ['taco-night', 'beef', 'kid-friendly'],
    estimatedCost: 14,
    servings: 4,
  }),
  r({
    id: 'r-satay',
    title: 'Chicken Satay Skewers with Peanut Sauce',
    ingredients: [
      { name: 'chicken thighs', quantity: 1.5, unit: 'lb' },
      { name: 'peanut butter', quantity: 0.5, unit: 'cup' },
      { name: 'soy sauce', quantity: 3, unit: 'tbsp' },
      { name: 'lime', quantity: 1, unit: 'count' },
      { name: 'garlic', quantity: 3, unit: 'clove' },
      { name: 'rice', quantity: 1.5, unit: 'cup' },
    ],
    allergens: ['peanut', 'soy', 'gluten'],
    tags: ['grill', 'chicken'],
    estimatedCost: 13,
    servings: 4,
  }),
  r({
    id: 'r-peanut-noodles',
    title: 'Takeout-Style Peanut Noodles',
    ingredients: [
      { name: 'noodles', quantity: 12, unit: 'oz' },
      { name: 'peanut butter', quantity: 0.33, unit: 'cup' },
      { name: 'soy sauce', quantity: 2, unit: 'tbsp' },
      { name: 'scallions', quantity: 4, unit: 'count' },
      { name: 'cucumber', quantity: 1, unit: 'count' },
    ],
    allergens: ['peanut', 'gluten', 'soy'],
    tags: ['pasta', 'vegetarian', 'quick'],
    estimatedCost: 9,
    servings: 4,
  }),
  r({
    id: 'r-sheetpan-chicken',
    title: 'Sheet-Pan Lemon Chicken and Potatoes',
    ingredients: [
      { name: 'chicken thighs', quantity: 2, unit: 'lb' },
      { name: 'potatoes', quantity: 2, unit: 'lb' },
      { name: 'lemon', quantity: 2, unit: 'count' },
      { name: 'olive oil', quantity: 3, unit: 'tbsp' },
      { name: 'garlic', quantity: 4, unit: 'clove' },
    ],
    allergens: [],
    tags: ['sheet-pan', 'chicken', 'kid-friendly'],
    estimatedCost: 11,
    servings: 4,
  }),
  r({
    id: 'r-spaghetti',
    title: 'Weeknight Spaghetti and Meat Sauce',
    ingredients: [
      { name: 'spaghetti', quantity: 1, unit: 'lb' },
      { name: 'ground beef', quantity: 1, unit: 'lb' },
      { name: 'crushed tomatoes', quantity: 28, unit: 'oz' },
      { name: 'onion', quantity: 1, unit: 'count' },
      { name: 'garlic', quantity: 3, unit: 'clove' },
      { name: 'parmesan cheese', quantity: 2, unit: 'oz' },
    ],
    allergens: ['gluten', 'dairy'],
    tags: ['pasta', 'beef', 'kid-friendly'],
    estimatedCost: 12,
    servings: 4,
  }),
  r({
    id: 'r-blackbean-tacos',
    title: 'Black Bean and Corn Tacos',
    ingredients: [
      { name: 'corn tortillas', quantity: 8, unit: 'count' },
      { name: 'black beans', quantity: 2, unit: 'can' },
      { name: 'frozen corn', quantity: 1, unit: 'cup' },
      { name: 'avocado', quantity: 2, unit: 'count' },
      { name: 'lime', quantity: 1, unit: 'count' },
    ],
    allergens: [],
    tags: ['tacos', 'vegetarian', 'quick'],
    estimatedCost: 9,
    servings: 4,
  }),
  r({
    id: 'r-salmon',
    title: 'Roasted Salmon with Rice and Broccoli',
    ingredients: [
      { name: 'salmon', quantity: 1.5, unit: 'lb' },
      { name: 'rice', quantity: 1.5, unit: 'cup' },
      { name: 'broccoli', quantity: 1, unit: 'lb' },
      { name: 'olive oil', quantity: 2, unit: 'tbsp' },
      { name: 'lemon', quantity: 1, unit: 'count' },
    ],
    allergens: ['fish'],
    tags: ['seafood', 'quick'],
    estimatedCost: 16,
    servings: 4,
  }),
  r({
    id: 'r-chili',
    title: 'Slow-Cooker Beef and Bean Chili',
    ingredients: [
      { name: 'ground beef', quantity: 1, unit: 'lb' },
      { name: 'kidney beans', quantity: 2, unit: 'can' },
      { name: 'crushed tomatoes', quantity: 28, unit: 'oz' },
      { name: 'onion', quantity: 1, unit: 'count' },
      { name: 'bell peppers', quantity: 2, unit: 'count' },
    ],
    allergens: [],
    tags: ['slow-cooker', 'beef', 'soup'],
    estimatedCost: 12,
    servings: 4,
  }),
  r({
    id: 'r-quesadillas',
    title: 'Chicken Quesadillas',
    ingredients: [
      { name: 'flour tortillas', quantity: 8, unit: 'count' },
      { name: 'cooked chicken', quantity: 2, unit: 'cup' },
      { name: 'cheddar cheese', quantity: 8, unit: 'oz' },
      { name: 'bell peppers', quantity: 1, unit: 'count' },
      { name: 'sour cream', quantity: 0.5, unit: 'cup' },
    ],
    allergens: ['gluten', 'dairy'],
    tags: ['quick', 'chicken', 'kid-friendly'],
    estimatedCost: 10,
    servings: 4,
  }),
  r({
    id: 'r-stirfry',
    title: 'Vegetable Tofu Stir-Fry',
    ingredients: [
      { name: 'tofu', quantity: 14, unit: 'oz' },
      { name: 'soy sauce', quantity: 3, unit: 'tbsp' },
      { name: 'broccoli', quantity: 1, unit: 'lb' },
      { name: 'carrots', quantity: 3, unit: 'count' },
      { name: 'rice', quantity: 1.5, unit: 'cup' },
    ],
    allergens: ['soy', 'gluten'],
    tags: ['vegetarian', 'quick'],
    estimatedCost: 9,
    servings: 4,
  }),
  r({
    id: 'r-pot-roast',
    title: 'Sunday Pot Roast',
    ingredients: [
      { name: 'chuck roast', quantity: 3, unit: 'lb' },
      { name: 'potatoes', quantity: 2, unit: 'lb' },
      { name: 'carrots', quantity: 6, unit: 'count' },
      { name: 'onion', quantity: 2, unit: 'count' },
      { name: 'beef broth', quantity: 2, unit: 'cup' },
    ],
    allergens: [],
    tags: ['slow-cooker', 'beef'],
    estimatedCost: 16,
    servings: 4,
  }),
  r({
    id: 'r-tomato-soup',
    title: 'Tomato Soup and Grilled Cheese',
    ingredients: [
      { name: 'crushed tomatoes', quantity: 28, unit: 'oz' },
      { name: 'heavy cream', quantity: 0.5, unit: 'cup' },
      { name: 'bread', quantity: 8, unit: 'count' },
      { name: 'cheddar cheese', quantity: 8, unit: 'oz' },
      { name: 'butter', quantity: 3, unit: 'tbsp' },
    ],
    allergens: ['dairy', 'gluten'],
    tags: ['soup', 'vegetarian', 'kid-friendly'],
    estimatedCost: 9,
    servings: 4,
  }),
  r({
    id: 'r-fajitas',
    title: 'Chicken Fajitas',
    ingredients: [
      { name: 'chicken breast', quantity: 1.5, unit: 'lb' },
      { name: 'bell peppers', quantity: 3, unit: 'count' },
      { name: 'onion', quantity: 2, unit: 'count' },
      { name: 'flour tortillas', quantity: 8, unit: 'count' },
      { name: 'lime', quantity: 2, unit: 'count' },
    ],
    allergens: ['gluten'],
    tags: ['chicken', 'quick'],
    estimatedCost: 13,
    servings: 4,
  }),
  r({
    id: 'r-fried-rice',
    title: 'Vegetable Fried Rice',
    ingredients: [
      { name: 'rice', quantity: 2, unit: 'cup' },
      { name: 'eggs', quantity: 3, unit: 'count' },
      { name: 'frozen peas', quantity: 1, unit: 'cup' },
      { name: 'carrots', quantity: 2, unit: 'count' },
      { name: 'soy sauce', quantity: 3, unit: 'tbsp' },
    ],
    allergens: ['egg', 'soy', 'gluten'],
    tags: ['vegetarian', 'quick'],
    estimatedCost: 8,
    servings: 4,
  }),
  r({
    id: 'r-baked-ziti',
    title: 'Baked Ziti',
    ingredients: [
      { name: 'pasta', quantity: 1, unit: 'lb' },
      { name: 'marinara sauce', quantity: 24, unit: 'oz' },
      { name: 'mozzarella', quantity: 8, unit: 'oz' },
      { name: 'ricotta', quantity: 1, unit: 'cup' },
      { name: 'parmesan cheese', quantity: 2, unit: 'oz' },
    ],
    allergens: ['gluten', 'dairy'],
    tags: ['pasta', 'vegetarian', 'kid-friendly'],
    estimatedCost: 11,
    servings: 4,
  }),
  r({
    id: 'r-pork-chops',
    title: 'Skillet Pork Chops with Apples',
    ingredients: [
      { name: 'pork chops', quantity: 4, unit: 'count' },
      { name: 'apples', quantity: 3, unit: 'count' },
      { name: 'onion', quantity: 1, unit: 'count' },
      { name: 'butter', quantity: 2, unit: 'tbsp' },
    ],
    allergens: ['dairy'],
    tags: ['pork', 'quick'],
    estimatedCost: 13,
    servings: 4,
  }),
  r({
    id: 'r-lentil-soup',
    title: 'Red Lentil Soup',
    ingredients: [
      { name: 'red lentils', quantity: 1.5, unit: 'cup' },
      { name: 'carrots', quantity: 3, unit: 'count' },
      { name: 'onion', quantity: 1, unit: 'count' },
      { name: 'vegetable broth', quantity: 6, unit: 'cup' },
      { name: 'lemon', quantity: 1, unit: 'count' },
    ],
    allergens: [],
    tags: ['soup', 'vegetarian'],
    estimatedCost: 7,
    servings: 4,
  }),
  r({
    id: 'r-shrimp-scampi',
    title: 'Shrimp Scampi',
    ingredients: [
      { name: 'shrimp', quantity: 1, unit: 'lb' },
      { name: 'spaghetti', quantity: 12, unit: 'oz' },
      { name: 'butter', quantity: 4, unit: 'tbsp' },
      { name: 'garlic', quantity: 5, unit: 'clove' },
      { name: 'lemon', quantity: 1, unit: 'count' },
    ],
    allergens: ['shellfish', 'gluten', 'dairy'],
    tags: ['pasta', 'seafood'],
    estimatedCost: 15,
    servings: 4,
  }),
  r({
    id: 'r-bbq-chicken',
    title: 'Oven BBQ Chicken Thighs',
    ingredients: [
      { name: 'chicken thighs', quantity: 2, unit: 'lb' },
      { name: 'barbecue sauce', quantity: 1, unit: 'cup' },
      { name: 'potatoes', quantity: 2, unit: 'lb' },
      { name: 'green beans', quantity: 1, unit: 'lb' },
    ],
    allergens: [],
    tags: ['chicken', 'kid-friendly'],
    estimatedCost: 12,
    servings: 4,
  }),
  r({
    id: 'r-minestrone',
    title: 'Minestrone',
    ingredients: [
      { name: 'pasta', quantity: 8, unit: 'oz' },
      { name: 'white beans', quantity: 2, unit: 'can' },
      { name: 'zucchini', quantity: 2, unit: 'count' },
      { name: 'carrots', quantity: 2, unit: 'count' },
      { name: 'vegetable broth', quantity: 4, unit: 'cup' },
    ],
    allergens: ['gluten'],
    tags: ['soup', 'vegetarian'],
    estimatedCost: 8,
    servings: 4,
  }),
  r({
    id: 'r-beef-stirfry',
    title: 'Beef and Broccoli Stir-Fry',
    ingredients: [
      { name: 'flank steak', quantity: 1, unit: 'lb' },
      { name: 'broccoli', quantity: 1.5, unit: 'lb' },
      { name: 'soy sauce', quantity: 4, unit: 'tbsp' },
      { name: 'rice', quantity: 1.5, unit: 'cup' },
      { name: 'garlic', quantity: 3, unit: 'clove' },
    ],
    allergens: ['soy', 'gluten'],
    tags: ['beef', 'quick'],
    estimatedCost: 14,
    servings: 4,
  }),
  r({
    id: 'r-margherita',
    title: 'Skillet Margherita Flatbread',
    ingredients: [
      { name: 'flour', quantity: 2, unit: 'cup' },
      { name: 'mozzarella', quantity: 8, unit: 'oz' },
      { name: 'tomatoes', quantity: 3, unit: 'count' },
      { name: 'basil', quantity: 1, unit: 'count' },
      { name: 'olive oil', quantity: 2, unit: 'tbsp' },
    ],
    allergens: ['gluten', 'dairy'],
    tags: ['vegetarian', 'kid-friendly'],
    estimatedCost: 8,
    servings: 4,
  }),
  r({
    id: 'r-tilapia',
    title: 'Crispy Baked Tilapia',
    ingredients: [
      { name: 'tilapia', quantity: 1.5, unit: 'lb' },
      { name: 'breadcrumbs', quantity: 1, unit: 'cup' },
      { name: 'eggs', quantity: 2, unit: 'count' },
      { name: 'lemon', quantity: 1, unit: 'count' },
      { name: 'green beans', quantity: 1, unit: 'lb' },
    ],
    allergens: ['fish', 'gluten', 'egg'],
    tags: ['seafood', 'quick'],
    estimatedCost: 12,
    servings: 4,
  }),
  r({
    id: 'r-stuffed-peppers',
    title: 'Stuffed Bell Peppers',
    ingredients: [
      { name: 'bell peppers', quantity: 4, unit: 'count' },
      { name: 'ground turkey', quantity: 1, unit: 'lb' },
      { name: 'rice', quantity: 1, unit: 'cup' },
      { name: 'crushed tomatoes', quantity: 14, unit: 'oz' },
      { name: 'cheddar cheese', quantity: 4, unit: 'oz' },
    ],
    allergens: ['dairy'],
    tags: ['kid-friendly'],
    estimatedCost: 12,
    servings: 4,
  }),
  r({
    id: 'r-chicken-soup',
    title: 'Chicken Noodle Soup',
    ingredients: [
      { name: 'cooked chicken', quantity: 2, unit: 'cup' },
      { name: 'egg noodles', quantity: 8, unit: 'oz' },
      { name: 'carrots', quantity: 3, unit: 'count' },
      { name: 'celery', quantity: 3, unit: 'count' },
      { name: 'chicken broth', quantity: 8, unit: 'cup' },
    ],
    allergens: ['gluten', 'egg'],
    tags: ['soup', 'chicken', 'kid-friendly'],
    estimatedCost: 9,
    servings: 4,
  }),
  r({
    id: 'r-veggie-curry',
    title: 'Chickpea Coconut Curry',
    ingredients: [
      { name: 'chickpeas', quantity: 2, unit: 'can' },
      { name: 'coconut milk', quantity: 14, unit: 'oz' },
      { name: 'spinach', quantity: 5, unit: 'oz' },
      { name: 'onion', quantity: 1, unit: 'count' },
      { name: 'rice', quantity: 1.5, unit: 'cup' },
    ],
    // 'coconut milk' trips the dairy term 'milk': the table over-blocks by
    // design, so the declaration carries it rather than fighting it.
    allergens: ['dairy'],
    tags: ['vegetarian', 'quick'],
    estimatedCost: 9,
    servings: 4,
  }),
  r({
    id: 'r-meatloaf',
    title: 'Classic Meatloaf',
    ingredients: [
      { name: 'ground beef', quantity: 1.5, unit: 'lb' },
      { name: 'breadcrumbs', quantity: 1, unit: 'cup' },
      { name: 'eggs', quantity: 2, unit: 'count' },
      { name: 'onion', quantity: 1, unit: 'count' },
      { name: 'potatoes', quantity: 2, unit: 'lb' },
    ],
    allergens: ['gluten', 'egg'],
    tags: ['beef', 'kid-friendly'],
    estimatedCost: 12,
    servings: 4,
  }),
  r({
    id: 'r-greek-bowls',
    title: 'Greek Chicken Bowls',
    ingredients: [
      { name: 'chicken breast', quantity: 1.5, unit: 'lb' },
      { name: 'rice', quantity: 1.5, unit: 'cup' },
      { name: 'cucumber', quantity: 1, unit: 'count' },
      { name: 'tomatoes', quantity: 2, unit: 'count' },
      { name: 'feta', quantity: 4, unit: 'oz' },
    ],
    // Feta is dairy even though the table has no 'feta' term.
    allergens: ['dairy'],
    tags: ['chicken', 'quick'],
    estimatedCost: 13,
    servings: 4,
  }),
  r({
    id: 'r-pulled-pork',
    title: 'Slow-Cooker Pulled Pork Sandwiches',
    ingredients: [
      { name: 'pork shoulder', quantity: 3, unit: 'lb' },
      { name: 'barbecue sauce', quantity: 1.5, unit: 'cup' },
      { name: 'sandwich buns', quantity: 8, unit: 'count' },
      { name: 'coleslaw mix', quantity: 14, unit: 'oz' },
    ],
    // Buns are wheat even though the table has no 'buns' term.
    allergens: ['gluten'],
    tags: ['slow-cooker', 'pork'],
    estimatedCost: 13,
    servings: 4,
  }),
  r({
    id: 'r-frittata',
    title: 'Veggie Frittata Night',
    ingredients: [
      { name: 'eggs', quantity: 8, unit: 'count' },
      { name: 'potatoes', quantity: 1, unit: 'lb' },
      { name: 'spinach', quantity: 5, unit: 'oz' },
      { name: 'cheddar cheese', quantity: 4, unit: 'oz' },
      { name: 'onion', quantity: 1, unit: 'count' },
    ],
    allergens: ['egg', 'dairy'],
    tags: ['vegetarian', 'quick'],
    estimatedCost: 8,
    servings: 4,
  }),
  r({
    id: 'r-fish-tacos',
    title: 'Baja Fish Tacos',
    ingredients: [
      { name: 'cod', quantity: 1.5, unit: 'lb' },
      { name: 'corn tortillas', quantity: 8, unit: 'count' },
      { name: 'cabbage', quantity: 0.5, unit: 'count' },
      { name: 'lime', quantity: 2, unit: 'count' },
      { name: 'sour cream', quantity: 0.5, unit: 'cup' },
    ],
    allergens: ['fish', 'dairy'],
    tags: ['tacos', 'seafood'],
    estimatedCost: 14,
    servings: 4,
  }),
  r({
    id: 'r-mac-cheese',
    title: 'Stovetop Mac and Cheese with Peas',
    ingredients: [
      { name: 'pasta', quantity: 1, unit: 'lb' },
      { name: 'cheddar cheese', quantity: 12, unit: 'oz' },
      { name: 'milk', quantity: 2, unit: 'cup' },
      { name: 'butter', quantity: 3, unit: 'tbsp' },
      { name: 'frozen peas', quantity: 1.5, unit: 'cup' },
    ],
    allergens: ['gluten', 'dairy'],
    tags: ['pasta', 'vegetarian', 'kid-friendly'],
    estimatedCost: 8,
    servings: 4,
  }),
  r({
    id: 'r-turkey-burgers',
    title: 'Turkey Burgers and Sweet Potato Fries',
    ingredients: [
      { name: 'ground turkey', quantity: 1.5, unit: 'lb' },
      { name: 'sandwich buns', quantity: 4, unit: 'count' },
      { name: 'sweet potatoes', quantity: 2, unit: 'lb' },
      { name: 'mayonnaise', quantity: 0.25, unit: 'cup' },
    ],
    allergens: ['gluten', 'egg'],
    tags: ['quick', 'kid-friendly'],
    estimatedCost: 12,
    servings: 4,
  }),
  r({
    id: 'r-white-chili',
    title: 'White Bean Chicken Chili',
    ingredients: [
      { name: 'chicken breast', quantity: 1, unit: 'lb' },
      { name: 'white beans', quantity: 2, unit: 'can' },
      { name: 'salsa verde', quantity: 16, unit: 'oz' },
      { name: 'chicken broth', quantity: 4, unit: 'cup' },
      { name: 'sour cream', quantity: 0.5, unit: 'cup' },
    ],
    allergens: ['dairy'],
    tags: ['soup', 'slow-cooker', 'chicken'],
    estimatedCost: 11,
    servings: 4,
  }),
  r({
    id: 'r-gnocchi',
    title: 'Sheet-Pan Gnocchi and Vegetables',
    ingredients: [
      { name: 'gnocchi', quantity: 1, unit: 'lb' },
      { name: 'cherry tomatoes', quantity: 1, unit: 'pint' },
      { name: 'zucchini', quantity: 2, unit: 'count' },
      { name: 'parmesan cheese', quantity: 2, unit: 'oz' },
      { name: 'olive oil', quantity: 3, unit: 'tbsp' },
    ],
    // Gnocchi is wheat even though the table has no 'gnocchi' term.
    allergens: ['gluten', 'dairy'],
    tags: ['sheet-pan', 'vegetarian', 'quick'],
    estimatedCost: 10,
    servings: 4,
  }),
  r({
    id: 'r-carnitas',
    title: 'Pork Carnitas Bowls',
    ingredients: [
      { name: 'pork shoulder', quantity: 2.5, unit: 'lb' },
      { name: 'rice', quantity: 1.5, unit: 'cup' },
      { name: 'black beans', quantity: 1, unit: 'can' },
      { name: 'lime', quantity: 2, unit: 'count' },
      { name: 'onion', quantity: 1, unit: 'count' },
    ],
    allergens: [],
    tags: ['slow-cooker', 'pork'],
    estimatedCost: 14,
    servings: 4,
  }),
  r({
    id: 'r-rice-noodles',
    title: 'Weeknight Rice Noodle Stir-Fry',
    ingredients: [
      { name: 'rice vermicelli', quantity: 8, unit: 'oz' },
      { name: 'eggs', quantity: 2, unit: 'count' },
      { name: 'carrots', quantity: 2, unit: 'count' },
      { name: 'scallions', quantity: 4, unit: 'count' },
      { name: 'fish sauce', quantity: 2, unit: 'tbsp' },
    ],
    allergens: ['egg', 'fish'],
    tags: ['quick'],
    estimatedCost: 9,
    servings: 4,
  }),
  r({
    id: 'r-caprese-orzo',
    title: 'Caprese Orzo with White Beans',
    ingredients: [
      { name: 'orzo', quantity: 12, unit: 'oz' },
      { name: 'mozzarella', quantity: 8, unit: 'oz' },
      { name: 'cherry tomatoes', quantity: 1, unit: 'pint' },
      { name: 'white beans', quantity: 1, unit: 'can' },
      { name: 'basil', quantity: 1, unit: 'count' },
    ],
    // Orzo is wheat even though the table has no 'orzo' term.
    allergens: ['gluten', 'dairy'],
    tags: ['pasta', 'vegetarian', 'quick'],
    estimatedCost: 9,
    servings: 4,
  }),
  r({
    id: 'r-drumsticks',
    title: 'Honey-Garlic Drumsticks',
    ingredients: [
      { name: 'chicken drumsticks', quantity: 2.5, unit: 'lb' },
      { name: 'honey', quantity: 0.33, unit: 'cup' },
      { name: 'soy sauce', quantity: 3, unit: 'tbsp' },
      { name: 'garlic', quantity: 4, unit: 'clove' },
      { name: 'rice', quantity: 1.5, unit: 'cup' },
    ],
    allergens: ['soy', 'gluten'],
    tags: ['chicken', 'kid-friendly'],
    estimatedCost: 11,
    servings: 4,
  }),
  r({
    id: 'r-veggie-chili',
    title: 'Three-Bean Vegetable Chili',
    ingredients: [
      { name: 'kidney beans', quantity: 1, unit: 'can' },
      { name: 'black beans', quantity: 1, unit: 'can' },
      { name: 'pinto beans', quantity: 1, unit: 'can' },
      { name: 'crushed tomatoes', quantity: 28, unit: 'oz' },
      { name: 'bell peppers', quantity: 2, unit: 'count' },
    ],
    allergens: [],
    tags: ['vegetarian', 'soup', 'slow-cooker'],
    estimatedCost: 8,
    servings: 4,
  }),
];

export interface SeedPriceHint extends Omit<PriceHint, 'seenAt'> {
  seenDaysAgo: number;
}

export const priceHints: SeedPriceHint[] = [
  { itemName: 'ground beef', store: 'Valu-Mart', price: 4.99, unit: 'lb', seenDaysAgo: 6 },
  { itemName: 'ground beef', store: 'Greenfield Market', price: 5.79, unit: 'lb', seenDaysAgo: 4 },
  { itemName: 'chicken thighs', store: 'Valu-Mart', price: 2.99, unit: 'lb', seenDaysAgo: 6 },
  { itemName: 'chicken thighs', store: 'Corner Fresh', price: 3.49, unit: 'lb', seenDaysAgo: 10 },
  { itemName: 'chicken breast', store: 'Greenfield Market', price: 4.29, unit: 'lb', seenDaysAgo: 4 },
  { itemName: 'flour tortillas', store: 'Valu-Mart', price: 0.31, unit: 'count', seenDaysAgo: 6 },
  { itemName: 'cheddar cheese', store: 'Valu-Mart', price: 0.44, unit: 'oz', seenDaysAgo: 6 },
  { itemName: 'cheddar cheese', store: 'Greenfield Market', price: 0.52, unit: 'oz', seenDaysAgo: 4 },
  { itemName: 'salmon', store: 'Corner Fresh', price: 9.99, unit: 'lb', seenDaysAgo: 10 },
  { itemName: 'salmon', store: 'Valu-Mart', price: 10.99, unit: 'lb', seenDaysAgo: 6 },
  { itemName: 'spaghetti', store: 'Greenfield Market', price: 1.79, unit: 'lb', seenDaysAgo: 25 },
  { itemName: 'black beans', store: 'Valu-Mart', price: 0.89, unit: 'can', seenDaysAgo: 35 },
  { itemName: 'crushed tomatoes', store: 'Valu-Mart', price: 0.07, unit: 'oz', seenDaysAgo: 35 },
  { itemName: 'pork shoulder', store: 'Corner Fresh', price: 2.49, unit: 'lb', seenDaysAgo: 12 },
  { itemName: 'shrimp', store: 'Corner Fresh', price: 8.99, unit: 'lb', seenDaysAgo: 10 },
];
